In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [26]:
dataset = pd.read_csv('bank-full.csv',header=0,sep=';')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values
dataset.dropna()
dataset.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [27]:
dataset['y'].value_counts()

no     39922
yes     5289
Name: y, dtype: int64

In [28]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['y'] = le.fit_transform(dataset['y'])

In [29]:
dataset.groupby('marital').mean()


age      balance        day    duration  campaign      pdays  \
marital                                                                        
divorced  45.782984  1178.872287  15.796428  262.517188  2.630882  41.001728   
married   43.408099  1425.925590  15.854487  253.412765  2.842875  37.950467   
single    33.703440  1301.497654  15.708210  266.497967  2.649805  44.652385   

          previous         y  
marital                       
divorced  0.551373  0.119455  
married   0.556552  0.101235  
single    0.642690  0.149492

In [30]:
dataset.groupby('education').mean()

age      balance        day    duration  campaign      pdays  \
education                                                                       
primary    45.865567  1250.949934  15.421398  255.933002  2.834331  36.081740   
secondary  39.964270  1154.880786  15.759159  258.685760  2.700802  42.353504   
tertiary   39.593640  1758.416435  16.086535  258.518532  2.825577  39.024134   
unknown    44.510501  1526.754443  15.810985  257.313947  2.849219  36.856220   

           previous         y  
education                      
primary    0.489272  0.086265  
secondary  0.567753  0.105594  
tertiary   0.661980  0.150064  
unknown    0.488422  0.135703

In [31]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,2,3,4,6,7,8,10,15])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
print(X)
print(len(X))

[[0.0 0.0 0.0 ... 1 -1 0]
 [0.0 0.0 0.0 ... 1 -1 0]
 [0.0 0.0 1.0 ... 1 -1 0]
 ...
 [0.0 0.0 0.0 ... 5 184 3]
 [0.0 1.0 0.0 ... 4 -1 0]
 [0.0 0.0 1.0 ... 2 188 11]]
45211


In [32]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
print(len(X_train))

31647


In [ ]:
X1_train = pd.DataFrame(X_train)
columns=X1_train.columns
print(X1_train)
print(columns)

In [44]:
from imblearn.over_sampling import SMOTE
os = SMOTE(random_state=0)

os_data_X,os_data_y=os.fit_resample(X_train, Y_train)
os_data_X = pd.DataFrame(data=os_data_X)
os_data_y= pd.DataFrame(data=os_data_y)

os_data_y[0].value_counts()

no     27953
yes    27953
Name: 0, dtype: int64

In [46]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

lr = LogisticRegression()
lr.fit(os_data_X, os_data_y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [47]:
y_pred = lr.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(lr.score(X_test, Y_test)))

Accuracy of logistic regression classifier on test set: 0.84


In [48]:
print(len(y_pred))

13564


In [49]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_test, y_pred)
print(confusion_matrix)

[[10131  1838]
 [  299  1296]]


In [50]:
from sklearn.metrics import classification_report
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

          no       0.97      0.85      0.90     11969
         yes       0.41      0.81      0.55      1595

    accuracy                           0.84     13564
   macro avg       0.69      0.83      0.73     13564
weighted avg       0.91      0.84      0.86     13564



In [51]:
Z = [25,'student','single','secondary','no',331,'no','no','telephone',26,'aug',170,4,-1,0,'unknown']
Z = pd.DataFrame(Z)
Z= Z.transpose()
Z=np.array(ct.transform(Z))
Z=scaler.transform(Z)
print(Z)

[[-0.35736906 -0.52358037 -0.18552227 -0.16411333 -0.51705911 -0.22885432
  -0.19074403 -0.31876039  6.9383935  -0.4509476  -0.17157667 -0.07833227
  -0.36280038 -1.22327872  1.58678822 -0.42221353  0.97253858 -0.64648269
  -0.20421819  0.13506755 -0.13506755  1.11991981 -1.11991981  0.43758857
  -0.43758857 -1.35677699  3.79177413 -0.63441447 -0.26152901  2.49837476
  -0.07195299 -0.24788219 -0.17988924 -0.42506704 -0.36324637 -0.10467601
  -0.66278584 -0.31325661 -0.12747029 -0.11256818 -0.34922134 -0.20580809
  -0.18515746  0.47245559 -1.50307194 -0.33544972  1.22504735 -0.34011795
   0.40713675 -0.41108056 -0.23732307]]


In [52]:
lr.predict(Z)

array(['no'], dtype=object)